title: "Alessandro Guasti"
author: "Alessandro Guasti"
description: "Esade Business School"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: "About Me"}
  - {file: "README.md", title: "Research"}
  - {file: "README.md", title: "Teaching"}
  - {url: "/CV_202501.pdf", title: "CV", icon: "file-pdf"}
  
external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:alessandro.guasti@esade.edu"}
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/alessandro-guasti-62a009ab/?originalSubdomain=uk"}
  - {title: Google Scholar, icon: graduation-cap, url: "https://scholar.google.com/citations?user=jkbjIRAAAAAJ&hl=it&oi=ao"}
  
comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
